name: CD

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Pack
        run: dotnet pack MetaphonePtBr/MetaphonePtBr.csproj -c Release -o nuget-package

      - name: NuGet Push
        run: dotnet nuget push nuget-package/*.nupkg -k ${{ secrets.API_KEY }} -s https://api.nuget.org/v3/index.json